
create database casestudy_feb28;
use casestudy_feb28;

select * from location;
select * from fact;
select * from product;

-- 1. Display the number of states present in the Location Table.
SELECT 
    COUNT(DISTINCT state)
FROM
    location;

-- 2. How many products are of regular type?
SELECT 
    COUNT(type)
FROM
    product
WHERE
    type = 'Regular';

-- 3. How much spending has been done on marketing of product ID 1?
SELECT 
    SUM(Marketing) AS TotalMarketing
FROM
    Fact
WHERE
    ProductID = 1;

-- 4. What is the minimum sales of a product?
SELECT 
    MIN(sales)
FROM
    fact;


-- 5. Display the max Cost of Good Sold (COGS).
SELECT 
    MAX(COGs)
FROM
    fact;


-- 6. Display the details of the product where product type is coffee.
SELECT 
    product, Product_Type
FROM
    product
WHERE
    Product_Type = 'Coffee';


-- 7. Display the details where total expenses are greater than 40.
SELECT 
    *
FROM
    fact
WHERE
    Total_Expenses > 40;

-- 8. What is the average sales in area code 719?
SELECT 
    AVG(sales)
FROM
    fact
WHERE
    Area_Code = 719;

-- 9. Find out the total profit generated by Colorado state.
SELECT 
    SUM(f.profit) AS total_profit
FROM
    fact f
        JOIN
    location l ON f.Area_Code = l.Area_Code
WHERE
    l.state = 'Colorado';

-- 10. Display the average inventory for each product ID. 
SELECT 
    productId, AVG(inventory) AS average_inventory
FROM
    fact
GROUP BY productId;


-- 11. Display state in a sequential order in a Location Table. 
SELECT 
    state
FROM
    location
ORDER BY state;

-- 12. Display the average budget of the Product where the average budget margin should be greater than 100. 
SELECT 
    productid, AVG(Budget_margin) AS avg_bgt
FROM
    fact
GROUP BY productid
HAVING AVG(Budget_Margin) > 100;

-- 13. What is the total sales done on date 2010-01-01?
SELECT 
    SUM(sales)
FROM
    fact
WHERE
    date = '2010-01-01';

-- 14. Display the average total expense of each product ID on an individual date. 
SELECT 
    date, productid, AVG(total_expenses) AS avg_totalexpenses
FROM
    fact
GROUP BY date , productid;

-- 15. Display the table with the following attributes such as date, productID, product_type, product, sales, profit, state, area_code. 
SELECT 
    f.date,
    f.productid,
    p.product_type,
    p.product,
    f.sales,
    f.profit,
    l.state,
    l.area_code
FROM
    fact f
        JOIN
    product p ON f.productid = p.ProductId
        JOIN
    location l ON f.area_code = l.Area_Code;



-- 16. Display the rank without any gap to show the sales wise rank. 
SELECT ProductID, Sales,
DENSE_RANK() OVER (ORDER BY Sales DESC) AS SalesRank
FROM fact;

-- 17. Find the state wise profit and sales. 
SELECT 
    l.state,
    SUM(f.profit) AS tot_profit,
    SUM(f.sales) AS tot_sales
FROM
    fact f
        JOIN
    location l ON f.Area_Code = l.Area_Code
GROUP BY l.state;

-- 18. Find the state wise profit and sales along with the productname. 
SELECT 
    l.state,
    p.product,
    SUM(f.profit) AS tot_profit,
    SUM(f.sales) AS tot_sales
FROM
    fact f
        JOIN
    location l ON f.Area_Code = l.Area_Code
        JOIN
    product p ON f.ProductId = p.ProductId
GROUP BY l.state , p.Product;



-- 19. If there is an increase in sales of 5%, calculate the increasedsales. 
SELECT 
    Sales, Sales + (Sales * 0.05) AS IncreasedSales
FROM
    fact;

-- 20. Find the maximum profit along with the product ID and producttype. 
SELECT TOP 1 F.ProductID, P.Product_Type, F.Profit
FROM Fact F
JOIN Product P ON F.ProductId = P.ProductId
ORDER BY F.Profit DESC;

-- 21. Create a stored procedure to fetch the result according to the product type from Product Table. 
SELECT * FROM Product;
Go
CREATE PROCEDURE GetProductByType
    @Product_Type VARCHAR(50)
AS
BEGIN
    SELECT *
    FROM Product
    WHERE Product_Type ='Espresso';
END;
EXEC GetProductByType @product_type='Coffee';

-- 22. Write a query by creating a condition in which if the total expenses is lessthan60 then it is a profit or else loss. 
SELECT ProductID, Total_Expenses,
CASE 
    WHEN Total_Expenses < 60 THEN 'Profit'
    ELSE 'Loss'
END AS Status
FROM Fact;

-- 23. Give the total weekly sales value with the date and product IDdetails. Useroll-up to pull the data in hierarchical order. 
SELECT DATEPART(WEEK, Date) AS WeekNo,
       ProductID,
       SUM(Sales) AS WeeklySales
FROM Fact
GROUP BY ROLLUP (DATEPART(WEEK, Date), ProductID);

-- 24.Apply union and intersection operator on the tables which consist of attribute area code. 
-- UNION
SELECT 
    Area_Code
FROM
    Fact 
UNION SELECT 
    Area_Code
FROM
    Location;

-- INTERSECT
SELECT 
    Area_Code
FROM
    Fact
INTERSECT SELECT 
    Area_Code
FROM
    Location;


-- 25. Change the product type from coffee to tea where product ID is 1 and undo it. 
BEGIN TRANSACTION;

UPDATE Product
SET Product_Type = 'Tea'
WHERE ProductID = 1;

-- Undo
ROLLBACK;

-- 26. Display the date, product ID and sales where total expenses are between 100 to 200. 
SELECT Date, ProductId, Sales
FROM fact
WHERE Total_Expenses BETWEEN 100 AND 200;

-- 27. Delete the records in the Product Table for regular type. 
DELETE FROM product
WHERE Type = 'Regular';

-- 28. Display the ASCII value of the fifth character from the columnProduct.
SELECT product,
       ASCII(SUBSTRING(Product, 5, 1)) AS ASCII_Value
FROM product;